version: '3'

services:
  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317" 
      - "4318:4318" 
      - "55680:55680"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

  spring-app:
    image: leonardozwirtes/pet-clinic:latest
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=java-demo
      - OTEL_TRACES_EXPORTER=otlp 
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_LOGS_LEVEL=INFO

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail-config.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail-config.yaml
    networks:
      - default

networks:
  default:
    driver: bridge
