receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  prometheus:
    config:
      scrape_configs:
        - job_name: "node_exporter"
          static_configs:
            - targets: ["node-exporter:9100"]
            # - targets: ['192.168.56.7:9100', '192.168.56.8:9100', '192.168.56.9:9100']

exporters:
  otlp:
    endpoint: https://tempo.elvenobservability.com/http:443
    headers:
      Authorization: "Bearer <API_TOKEN>"
      X-Scope-OrgID: "statix"

  prometheusremotewrite:
    endpoint: https://mimir.elvenobservability.com/api/v1/push
    headers:
      X-Scope-OrgID: "statix"
      Authorization: "Bearer <API_TOKEN>"

  otlphttp:
    endpoint: "http://loki.elvenobservability.com/loki/api/v1/push"
    headers:
      X-Scope-OrgID: "statix"
      Authorization: "Bearer <API_TOKEN>"

processors:
  batch: {}
  filter:
    metrics:
      exclude:
        match_type: regexp
        metric_names:
          - "go_.*"
          - "scrape_.*"
          - "otlp_.*"
          - "promhttp_.*"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, filter]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
